# Generated by Django 4.0.6 on 2022-07-10 20:04

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='avatar',
            field=models.ImageField(default='', upload_to=users.models.upload_to, verbose_name='Image'),
        ),
    ]
