version: '3.9'

services:

  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: tune
      POSTGRES_PASSWORD: tune
      POSTGRES_DB: tune
