# Generated by Django 4.0.6 on 2022-07-09 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tune_app', '0008_alter_album_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='image_url',
            field=models.ImageField(upload_to='tune_app'),
        ),
    ]
