# Generated by Django 4.0.6 on 2022-07-09 05:07

from django.db import migrations, models
import tune_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('tune_app', '0009_alter_artist_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='image_url',
            field=models.ImageField(upload_to=tune_app.models.upload_to),
        ),
    ]
