# Generated by Django 4.0.6 on 2022-07-09 05:40

from django.db import migrations, models
import tune_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('tune_app', '0010_alter_album_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='image_url',
        ),
        migrations.AddField(
            model_name='album',
            name='image',
            field=models.ImageField(default='tune_app/IMG_1717.jpg', upload_to=tune_app.models.upload_to, verbose_name='Image'),
        ),
    ]
