# Generated by Django 4.0.6 on 2022-07-12 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tune_app', '0011_remove_album_image_url_album_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='year',
            field=models.CharField(default='2022', max_length=4),
        ),
    ]
