# Generated by Django 4.0.6 on 2022-07-12 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tune_app', '0012_album_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='rating',
            field=models.CharField(default='1', max_length=1),
        ),
    ]
