# Generated by Django 4.0.6 on 2022-07-15 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tune_app', '0015_album_avg_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='album_list', to='tune_app.genre'),
        ),
    ]
