# Generated by Django 4.0.6 on 2022-07-15 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tune_app', '0016_alter_album_avg_rating_alter_album_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='post_list', to='tune_app.genre'),
        ),
    ]
