# Generated by Django 4.0.6 on 2022-07-20 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tune_app', '0017_post_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='bio',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='artist',
            name='birthday',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
