# Generated by Django 4.0.6 on 2022-07-20 19:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tune_app', '0018_artist_bio_artist_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='year',
        ),
        migrations.AddField(
            model_name='album',
            name='release',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
